name: adb_utils
description: A Dart library for interacting with ADB (Android Debug Bridge) server and devices.
version: 0.4.7
homepage: https://github.com/desodre/adb_utils
repository: https://github.com/desodre/adb_utils
issue_tracker: https://github.com/desodre/adb_utils/issues

platforms:
  windows:
  linux:
  macos:

environment:
  sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
  logging: ^1.3.0
  path: ^1.9.0
  xml: ">=6.0.0 < 8.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
